// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleArchitectureGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "SimpleArchitectureGenv1.af0b02be-d43b-45d1-ba43-7d214dd9c2bf";
        public const string Name = "Simple Architecture Code Generator V.1.3";
        public const string Description = @"This is code generator for SimpleArchitecture V.1.3";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Taner Saydam";
        public const string Tags = "";
    }
}
