// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleArchitectureGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "SimpleArchitectureGen.af0b02be-d43b-45d1-ba43-7d214dd9c2bf";
        public const string Name = "SimpleArchitectureGen";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Taner Saydam";
        public const string Tags = "";
    }
}
